ifndef TARGET
TARGET=sky
endif

CONTIKI_SOURCEFILES += sht11.c
APPS=serial-shell

CONTIKI_PROJECT = capteur_tempIn
all: $(CONTIKI_PROJECT)

#UIP_CONF_IPV6=1

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include

